---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# jbutilities_R

This package contains multiple functions in R I found or created through the years and may be useful to keep


## Installation

You can install the released version of jbutilities from [GITHUB](https://github.com/bronnimannj/jbutilities_r).



## Functions inside the package:

|      Function    | brief description                             |
|------------------|-----------------------------------------------|
|   create_df_rd   | Creates a random table                        |
<!-- |     dfdf         |                                               |



| check_format_df  | Verifies the format of a table                | -->

### cut_fat

This function is a fast version of cut that will put every element of x in one of the intervals created by breaks. Each interval is left closed and right opened, example: '[0,1)'.

If -Inf or/and +Inf are not in the vector 'breaks', it will be added to it.

If none of the elements are out of the intervales between the breaks, then the factor returned is only constituted of the breaks intervals. Else, +/-Inf will be added.

Inputs:

- x: Numeric vector of elements to put into segments
- breaks: Numeric vector of breaks

It returns a factor of intervals


### find_series

Function to find the latest file in a series. Types regognized are:

Inputs:

- Name String: representing the name of the file
- Type String: representing the extension of the file

It returns a String, with the last name of the series



### my_ggtheme

Function to put my favorite ggplot theme to any ggplot plot

Inputs:

- x_percent boolean, if TRUE we label the x axis into percents
- y_percent boolean, if TRUE we label the y axis with percents

It returns a ggplot with a new theme




### name_series

Function to create files without over writing them.

It will add an underscore and the next number of the series.

Inputs:

- Name: String, representing the name of the file
- Type: String, representing the extension of the file

It returns a String, with the next name of the series



### step_time

Function to print a step and time

Input: "step", a string character representing the step. Can be a number too

It returns a string containing the step and the date + time in a format "(X.Y) - [ 06/03/2021 18:03:32 ]"


