# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Mean per row
#'
#' Returns the average of the numeric values, row per row (similar as pmin)
#'
#' @param df DataFrame. Contains only numerical values
#' @param na_rm, boolean. Accept of not the NAs
#' @return NumericVector or mean values.
#' @export
#'
#' @examples pavg( data.frame(a = c(1,2,3), b = c(2,3,3)), na_rm = TRUE)
pavg <- function(df, na_rm) {
    .Call(`_jbutilities_pavg`, df, na_rm)
}

