# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rank A numerical dataset row by row
#'
#' Returns a data frame where each row is ordered. The columns names are "TOP" + the number.
#'
#' @param df DataFrame, Data frame numerical values (NA included).
#' @export
#'
#' @examples
#' rankdf(data.frame(x = c(3,4), y = c(5,6)))
rankdf <- function(df) {
    .Call('_jbutilities_rankdf', PACKAGE = 'jbutilities', df)
}

#' Rank numerical values
#'
#' Returns the rank of the a numerical column from a dataset of Numerical values
#'
#' @param values NumericVector, containing all the values to rank
#' @param df DataFrame, Data frame of values against we will rank (NA included).
#' @param method String, either "min", "avg" or "max". when there are equalities in the values.
#' @export
#'
#' @examples
#' ranker(c(1,2),data.frame(x = c(3,4),y = c(5,6)), "min")
#' ranker(10,data.frame(x = 10 , y = 10, z = 11, w = 12, u = 13),"min")
ranker <- function(values, df, method) {
    .Call('_jbutilities_ranker', PACKAGE = 'jbutilities', values, df, method)
}

